spring:
  application:
    name: ai-photo-service
  devtools:
    restart:
      enabled: true
  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/ai_photo?useSSL=false&serve
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.zaxxer.hikari.HikariDataSource
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456
      database: 6
      # 连接超时时间
      timeout: 10s
      lettuce:
        pool:
          # 连接池中的最小空闲连接
          min-idle: 0
          # 连接池中的最大空闲连接
          max-idle: 8
          # 连接池的最大数据库连接数
          max-active: 8
          # #连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms

server:
  port: 8011
  servlet:
    # 应用的访问路径
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

mybatis:
  mapper-locations: classpath:mapper/*.xml

# 接口文档配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v1/docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.yyp.aiphotoservice.controller
knife4j:
  enable: true
  setting:
    language: zh_cn
  # 开启生产环境屏蔽
  production: false
#  documents:
#    - group: 2.X版本
#      name: 接口签名
#  basic:
#    enable: false
#    username: admin
#    password: 123456